name: xteammors
description: "A smart IM client."

#publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.7.0"


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  record: ^6.1.2
  path_provider: ^2.1.3
  video_player: ^2.10.1
  audioplayers: ^6.5.1

  #Record sound service

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
